version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - "backend"